### ISSUE TITLE
gnuradio::gnuradio-network target was not found

### ISSUE THREAD

**Issue by e850205** [USA-RedDragon/trunk-recorder-prometheus#16]
Getting error building the plugin:

CMake Error at CMakeLists.txt:204 (add_library):
  Target "prometheus_plugin" links to target "gnuradio::gnuradio-network" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

**Comment by e850205** [comment]
I think I fixed it by removing line 213 from CMakeLists.txt, however the plugin needs updating to work with the current version of trunk-recorder.

**Comment by USA-RedDragon** [comment]
The opposite actually. If you want to use it with the current ([v4.6.0](https://github.com/robotastic/trunk-recorder/releases/tag/v4.6.0)) trunk-recorder you'll need to build the [v4.6.0 tag of this plugin](https://github.com/USA-RedDragon/trunk-recorder-prometheus/tree/v4.6.0). The current `main` of this plugin is for the not-yet-released v4.7.
